# backend-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
data:
  SQL_PASSWORD: UGFzc0BOZXdtMw==
  JWT_SECRET: NjQ3MlRZJl4zdHlydXd6NzczODM5YVVJSU9P
